### ISSUE TITLE
Decrease the healing probability and increase attack in entities2

### ISSUE THREAD

**Issue by Artezon** [norbcodes/entities#1]
Nice game, I would suggest a few improvements:

Healing and autohealing choices should appear less often for both player and AI because it's easy for both get a lot of HP and armor, so the game basically never ends. Please make attack choices appear more often, also I think regeneration should be nerfed and be very rare.

In addition you probably should cap HP at 100 and 
- [x] #7

![image](https://github.com/user-attachments/assets/1c98ed1a-61b8-465b-a429-73a66898d1de)

**Comment by norbcodes** [comment]
Oooo, poison sounds nice! Will do.
