### ISSUE TITLE
Seemingly unreproducible bug

### ISSUE THREAD

**Issue by norbcodes** [norbcodes/entities#10]
A good friend of mine, @MF366-Coding, found a very quirky bug that I cannot seem to reproduce.

Basically when the game gets to the stage of printing the entity stats, it gets stuck.
I have a few suspicions (like that while true loop) but I'm gonna need to do more tests with my homie to figure it out.

**Comment by mf366-dev** [comment]
I'll post the executable ASAP.

In the meanwhile, I will attempt to investigate whether this is a compilation bug of my g++.

Here is the picture of the bug:
![unreproducable_bug.png](https://github.com/user-attachments/assets/0fb15bb8-7a9b-4300-8907-431fbe1cfbf3)

**Comment by mf366-dev** [comment]
After a lot of investigation, me and @norbcodes came to the conclusion that this is a **compilation error** and **not** a bug. 

This has been confirmed by me. Sadly, I have no idea what happened to my MinGW installation but `g++` and `gcc `were invalid all along.

I'm sorry for all the work, Norb! I installed **MSYS2**, tried to compile and guess what? It worked just fine!

Awesome game!

**Comment by norbcodes** [comment]
The feeling when you don't have spend 8 hours fixing a bug 
![image](https://github.com/user-attachments/assets/fb3cc490-8985-458e-a69a-e4da069f3654)

**Comment by mf366-dev** [comment]
> The feeling when you don't have spend 8 hours fixing a bug 

A bug that does not even exist xDD
