### ISSUE TITLE
Completely Random Difficulty

### ISSUE THREAD

**Issue by mf366-dev** [norbcodes/entities#14]
So, you have **Easy/Medium/Hard**, right? What about a difficulty that is **completely** random. It could use RNG to give completely random and **unpredictable** values. What are your thoughts on this, @norbcodes :)

**Comment by norbcodes** [comment]
Hmmm, as in it could either pick values from one of the existing difficulties? Or does it generate absolutely crazy values (Like player health 15 armor 0 and enemy health 200 and 200 armor)?

**Comment by mf366-dev** [comment]
While the values are still based on RNG, basically it doesn't do difficulty checks. It just goes like "hmmm? So I got 20 HP for the player? Too bad, skill issue"

**Comment by norbcodes** [comment]
Ah, alright
