### ISSUE TITLE
Tips & Tricks and Quitting with 0

### ISSUE THREAD

**Issue by mf366-dev** [norbcodes/entities#17]
So 2 things:

- [x] #26
- [x] #27

So yeah, this is all :))

**Comment by norbcodes** [comment]
But if 0 can quit in any point in the game, what if the player on wants to exit from the battle using 0?

I'll do the 0 instead of 9 exit key, but not the second one, sorry.

**Comment by mf366-dev** [comment]
> But if 0 can quit in any point in the game, what if the player on wants to exit from the battle using 0?
> 
> I'll do the 0 instead of 9 exit key, but not the second one, sorry.

I did not understand, sorry.

My idea is Tips & Tricks, it is up to you to decide which tips you give the player.

**Comment by norbcodes** [comment]
Oh alright, but I guess I won't add `You can quit entities2 with 0 at all times.` since you will only use 0 to exit from the battle, not exit from the game entirely

**Comment by mf366-dev** [comment]
Ok, hope I helped :)))

**Comment by norbcodes** [comment]
Updated comment and splitted into 2 different issues

**Comment by mf366-dev** [comment]
Ok thanks
