### ISSUE TITLE
Energy system

### ISSUE THREAD

**Issue by norbcodes** [norbcodes/entities#5]
It would be cool if there was some sort of "energy" that regenerates every turn. Dealing more damage, healing more HP, etc. should require more energy. Otherwise no one would choose the weaker move. If this is going to be implemented, it should be done carefully, cause a player should always have anough energy to make a move and the energy should be enough unless player chooses the strongest move several times in a row.

[From #3]

**Comment by Artezon** [comment]
I have an idea about energy implementation, what if there was a basic ATK and a strong ATK, the basic one would regenerate one energy unit and the strong one would consume one energy unit? And energy would be capped at, say, 5 units? (Yes, I stole the idea from honkai)

**Comment by Artezon** [comment]
You can also add an ultimate that appears after you use a strong attack multiple times. This ultimate can be chosen at the beginning of the game, or it can be a random player buff or enemy debuff such as HP regen, crit rate increase, invisibility, poison effect, turn skip, etc.

**Comment by norbcodes** [comment]
I'll consider it, but I already have something in mind ;)
